/**
 * Shared utility for constructing image serve URLs.
 *
 * The backend exposes images at `/api/images/serve/{path}`.
 * In development the Vite proxy forwards `/api/*` to the backend,
 * so we use relative paths.  In production we prepend VITE_API_URL.
 */

const API_BASE = import.meta.env.PROD
  ? (import.meta.env.VITE_API_URL || 'http://localhost:8000')
  : '' // empty string in dev -> relative path -> Vite proxy

/**
 * Convert a backend image path (e.g. `data\storage\discovered\uuid.jpg`
 * or `/static/images/data/models/atrw/images/00001.jpg`) into a full
 * URL that the browser can load via the backend image-serve endpoint.
 *
 * If the value is already an absolute HTTP(S) URL it is returned as-is.
 * If the value is falsy, a placeholder path is returned.
 */
export function getImageUrl(imagePath: string | null | undefined): string {
  if (!imagePath) return '/placeholder-tiger.png'

  // Already a full URL -- return as-is
  if (imagePath.startsWith('http://') || imagePath.startsWith('https://')) {
    return imagePath
  }

  // Normalize Windows backslashes to forward slashes
  let normalized = imagePath.replace(/\\/g, '/')

  // If the backend already returned a path through the image-serve endpoint,
  // just prepend the API base (for prod) and return.
  if (normalized.startsWith('/api/images/serve/')) {
    return `${API_BASE}${normalized}`
  }
  if (normalized.startsWith('api/images/serve/')) {
    return `${API_BASE}/${normalized}`
  }

  // Strip leading slash so we don't get double-slashes in the URL
  normalized = normalized.replace(/^\/+/, '')

  // If the path was generated by tiger_routes as /static/images/...,
  // strip the /static/images/ prefix and serve via the image-serve endpoint
  if (normalized.startsWith('static/images/')) {
    normalized = normalized.replace(/^static\/images\//, '')
  }

  return `${API_BASE}/api/images/serve/${normalized}`
}
